name: angular-auction-ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: ngAuction

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache-dependency-path: 'ngAuction/package-lock.json'
        env:
          NODE_VERSION: '14.x'
      - run: npm ci
      - run: npm run test-ci
      - run: npm run build
      - name: Upload test artifact
        uses: actions/upload-artifact@v2
        with:
          name: ngAuction-coverage
          path: ngAuction/coverage/ngAuction
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: ngAuction-dist
          path: ngAuction/dist/ngAuction
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
